name: Humanize
identifier: com.pat.popclip.extension.humanize
icon: H
description: Humanizes text using fine-tuned Gemini API
shell script:
  script: |
    #!/bin/bash
    TEXT="$POPCLIP_TEXT"
    API_KEY="YOUR_API_KEY"
    MODEL="gemini-exp-1206"
    PAYLOAD="{\"contents\":[{\"parts\":[{\"text\":\"input: $TEXT\"}]}]}"
    RESPONSE=$(curl -s -X POST \
      "https://generativelanguage.googleapis.com/v1beta/models/$MODEL:generateContent?key=$API_KEY" \
      -H "Content-Type: application/json" \
      -d "$PAYLOAD")
    PROCESSED_TEXT=$(echo "$RESPONSE" | grep -o '"text":"[^"]*"' | cut -d'"' -f4)
    echo -n "$PROCESSED_TEXT" | pbcopy
after: paste-result
requirements:
  - paste
